format_version: v1.0
type: UniqueComponent
attributes: {id: sys_input}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: INPUT_SYS_RTOS_TASK_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: RTOSEnabled}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_input, value: 'false'}
  - type: Menu
    attributes: {id: RTOSMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '361', y: '47', id: sys_input}
