format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_maxtouch_controller}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_I2C_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: Asynchronous}
  - type: Integer
    attributes: {id: DRV_MAXTOUCH_I2C_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: '0'}
  - type: Integer
    attributes: {id: Height}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: '480'}
  - type: Integer
    attributes: {id: Width}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_maxtouch_controller, value: '800'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: i2c}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c}
  - type: DirectDependency
    attributes: {id: touch_panel}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_pdatm5000_800x480}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: touch_panel}
- type: ElementPosition
  attributes: {x: '540', y: '281', id: gfx_maxtouch_controller}
