configName: lcdc_rgba8888_mxt_a5d2_wvga
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMA5D27
projectName: ''
settings:
  PackageFilter: aerospace;audio;bsp;core;csp;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_RECENT
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.42\atdf\ATSAMA5D27.atdf
