format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_hal_le}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '480'}
  - type: Integer
    attributes: {id: DisplayHorzBackPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '40'}
  - type: Integer
    attributes: {id: DisplayHorzFrontPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '40'}
  - type: Integer
    attributes: {id: DisplayHorzPulseWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '48'}
  - type: Integer
    attributes: {id: DisplayVertBackPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '29'}
  - type: Integer
    attributes: {id: DisplayVertFrontPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '13'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '800'}
  - type: String
    attributes: {id: DriverName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: LE LCDC Driver}
  - type: Integer
    attributes: {id: PixelClock}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '23714285'}
  - type: Integer
    attributes: {id: RefreshRate}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal_le, value: '48'}
  - type: String
    attributes: {id: gfx_driver}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: le_gfx_lcdc}
- type: ElementPosition
  attributes: {x: '441', y: '20', id: gfx_hal_le}
