format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_lcdc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: BacklightPWMClockPrescaler}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm5000, value: '0'}
  - type: Combo
    attributes: {id: BacklightPWMClockSource}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm5000, value: CLK_SLOW}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '480'}
  - type: Menu
    attributes: {id: DisplaySettingsMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '800'}
  - type: Boolean
    attributes: {id: DoubleBuffer}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm5000, value: 'true'}
  - type: Comment
    attributes: {id: HALComment}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: PixelClock}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '27333333'}
  - type: Integer
    attributes: {id: PixelClockDiv}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm5000, value: '6'}
  - type: Integer
    attributes: {id: TotalNumLayers}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_lcdc, value: '3'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Graphics Display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_pdatm5000_800x480}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display}
  - type: DirectDependency
    attributes: {id: LCDC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lcdc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: LCDC_LCDC}
  - type: DirectCapability
    attributes: {id: le_gfx_driver_lcdc}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_legato}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver}
- type: ElementPosition
  attributes: {x: '390', y: '120', id: le_gfx_lcdc}
