format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_disp_pdatm5000_800x480}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: touch_panel}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_maxtouch_controller}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: touch_panel}
- type: ElementPosition
  attributes: {x: '50', y: '303', id: gfx_disp_pdatm5000_800x480}
