configName: lcdc_rgba8888_mxt_a5d27_som1_ek1_wvga
folderName: blank_cqs_a5d27_som1_ek1_tm5000
format_version: v1.0
frameworkPath: ..\..\..\..\..\Harmony3
processor: ATSAMA5D27CD1G
projectName: blank_cqs_a5d27_som1_ek1_tm5000
settings:
  PackageFilter: bsp;core;core_apps_pic32mz_da;core_apps_sam_9x60;core_apps_sam_a5d2;core_apps_sam_e70_s70_v70_v71;csp;csp_apps_pic32mz_da;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_e70_s70_v70_v71;Devices;dev_packs;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;gfx_apps_sam_a5d2;gfx_apps_sam_c20_c21;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_apps_sam_l22;harmony-services;quick_docs;touch;usb;usb_apps_device;usb_apps_host
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.7.91\atdf\ATSAMA5D27CD1G.atdf
