configName: lcdc_rgba8888_mxt_a5d2_wvga_iar
folderName: legato_qs_a5d2_xu_tm5000.IAR
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMA5D27
projectName: legato_qs_a5d2_xu_tm5000.IAR
settings:
  PackageFilter: bsp;core;core_apps_sam_9x60;core_apps_sam_a5d2;crypto;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2;gfx;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_RECENT
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.53\atdf\ATSAMA5D27.atdf
