configName: sam_a5d29_cu
folderName: embedded_wizard_db_sam_a5d29_cu_tm5000
format_version: v1.0
frameworkPath: C:\Users\i70650\Harmony610
processor: ATSAMA5D29
projectName: embedded_wizard_db_sam_a5d29_cu_tm5000
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMA5D2_DFP\1.10.213
