format_version: v1.0
type: UniqueComponent
attributes: {id: cam}
children:
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: i2c}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c}
  - type: DirectDependency
    attributes: {id: isc}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: isc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: isc}
- type: ElementPosition
  attributes: {x: '717', y: '155', id: cam}
