format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_disp_pdatm5000_800x480}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_lcdc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: Graphics Display}
- type: ElementPosition
  attributes: {x: '0', y: '126', id: gfx_disp_pdatm5000_800x480}
