format_version: v1.0
type: UniqueComponent
attributes: {id: isc}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: isc}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: cam}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: isc}
- type: ElementPosition
  attributes: {x: '484', y: '285', id: isc}
